<template>
  <div>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  <p>upload</p>
  </div>
</template>

<script>
export default {
  mounted () {
    console.log(this.$route)
  }
}
</script>
